server:
  port: 8081


spring:
    datasource:
      url: "jdbc:postgresql://localhost:5432/db_1"
      username: "postgres"
      password: "123"
      driver-class-name: "org.postgresql.Driver"

    jpa:
      generateDdl: "true"
      hibernate:
        ddlAuto: "update"
      showSql: "true"
      databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
      properties:
        hibernate:
          default_schema: "netology"

    servlet:
      multipart:
        maxFileSize: "104857600"
        maxRequestSize: "104857600"

jwt:
  signingKey: "ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ"

  
